#4
- name: Demo on play level variables
  hosts: all
  vars:
    url: play.example.com
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL - {{ url }}

#2
- name: Demo on task level variables
  hosts: all
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL - {{ url }}
      vars:
        url: tasks.example.com

#3
- name: load vars from file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL - {{ url }}


- name: variables from roles
  hosts: all
  vars:
    url_play: role.example.com
  roles:
    - sample

- name: demo on registered variables
  hosts: all
  tasks:
    - name: run uptime shell command
      ansible.builtin.shell: uptime




#- name: demo on registered variables
#  hosts: all
#  tasks:
#    - name: run uptime shell command
#      ansible.builtin.shell: uptime
#      register: output
#    - name: print output
#      ansible.built.debug:
#        msg: "{{ output }}"