- name: print a parameter
  hosts: all
  tasks:
    - name: print a parameter
      ansible.builtin.debug:
        msg: parameter-"{{ lookup('amazon.aws.aws_ssm', 'tesst.test', region='us-east-1' ) }}"
