- name: demo on loops
  hosts: localhost
  connection: local
  tasks:
  - name: demp tasks for loops
    ansible.builtin.debug:
      msg: fruit name - {{ item }}
    loop:
      - banana
      - mango

