- name: demo on loops
  hosts: localhost
  connection: local
  tasks:
  - name: demo tasks for loops
    ansible.builtin.debug:
      msg: fruit name - {{ item }}
    loop:
      - banana
      - mango

  - name: demo on loops1
    ansible.builtin.debug:
      msg: fruit name - {{ item.name }}, quantity - {{ item.quantity }}
    loop:
      - { mame: apple, quantity: 10 }
      - { name: mango, quantity: 15 }

